version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - stack.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - stack.env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html:ro
    restart: always
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.nextcloud2-rtr.entrypoints=https"
      - "traefik.http.routers.nextcloud2-rtr.rule=HostHeader(`nextcloud2.$DOMAINNAME`)"
      - "traefik.http.routers.nextcloud2-rtr.tls=true" 
      ## Middlewares
      # - "traefik.http.routers.organizr-rtr.middlewares=chain-oauth@file"
        # Redirect non-www to www middleware
      - "traefik.http.routers.nextcloud2-rtr.middlewares=nextcloud2-dav,chain-oauth@file" # Google OAuth 2.0
      - "traefik.http.middlewares.nextcloud2-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
      - "traefik.http.middlewares.nextcloud2-dav.replacepathregex.replacement=/remote.php/dav/"
      ## HTTP Services
      - "traefik.http.routers.nextcloud2-rtr.service=nextcloud2-svc"
      - "traefik.http.services.nextcloud2-svc.loadbalancer.server.port=443"
      - "traefik.http.services.nextcloud2-svc.loadbalancer.server.scheme=https"  
  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
